DROP TABLE BOOKINGS;
DROP TABLE PRODUCT_SUPPLIED;
DROP TABLE CUSTOMER_ORDER;
DROP TABLE TICKETS;
DROP TABLE EVENTS;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE PRODUCT;
DROP TABLE SUPPLIER;

DROP SEQUENCE Seq_Customer;
DROP SEQUENCE Seq_Bookings;
DROP SEQUENCE Seq_Employee;
DROP SEQUENCE Seq_Product;
DROP SEQUENCE Seq_Supplier;
DROP SEQUENCE Seq_Tickets;
DROP SEQUENCE Seq_Events;