CREATE TABLE EMPLOYEE(
    Emp_ID NUMBER(5) CONSTRAINT emp_id PRIMARY KEY,
    Emp_Fname VARCHAR2(30) NOT NULL,
    Emp_Lname VARCHAR2(30) NOT NULL,
    Emp_IDNum VARCHAR2(13) NOT NULL UNIQUE,
    Emp_email VARCHAR2(40) UNIQUE ,
    Emp_CellNum VARCHAR2(10) NOT NULL UNIQUE,
    Emp_Address VARCHAR2(40) NOT NULL,
    Emp_Type char(1) NOT NULL
);